CREATE TABLE follow
(id INT AUTO_INCREMENT PRIMARY KEY,
 user_id INT,
 follower_id INT,
 date DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id),
 FOREIGN KEY (follower_id) REFERENCES users(id));